language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../ArrayList
  - make -j
  - cd ./bin/
  - ./test_postfix --gtest_list_tests
notifications:
  email: alekshlybov23@gmail.com
